# 1. Create service account
#.   * Service Account Token Creator
#.   * Artifact Registry Writer
# 2. Generate service account key
#.   * In GitHub project -> Settings -> Secrets -> Actions -> New Repository Secret
#.     Name: GCP_CREDENTIALS
#.     Value: key.json contents
# 3. Create repo in artifact repository 
#.   * Name: $env.REPOSITORY below
#.   * Region: $env.GAR_LOCATION below

name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  GAR_LOCATION: europe-west2
  REPOSITORY: flux-system
  IMAGE: notification-controller
  IMAGE_VERSION: v1.4.0 # Can be replaced with GITHUB_SHA, the commit hash.

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest
    environment: cicd

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Docker build'
      run: |-
        docker build . --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$IMAGE_VERSION" \
        --file $REPOSITORY/$IMAGE/Dockerfile
      env:
        PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        token_format: 'access_token'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  
    - uses: 'docker/login-action@v1'
      name: 'Docker login'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Docker push'
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$IMAGE_VERSION"
      env:
        PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}

